### ISSUE TITLE
Multiple dialogs per UA per scenario

### ISSUE THREAD

**Issue by NGSegovia** [zaleos/sipplauncher#3]
## Description
SIPp can only handle 1 Dialog per scenario.
As a developer, I would like to be able to define 2 or more SIPp scenarios to be executed sequentially using the same UA IP address to allow creating scenarios that include more than 1 dialog per sipplauncher test run.
## Acceptance Criteria

More than 1 scenario XML file with the common prefix ua[cs]_uaX can be created
New scenario naming convention to clearly identify the order in which scenarios of the same UA will be executed
No separate before/after hooks are required for the each of sequentially run scenarios
Each of the scenario runtime logs to be available in a separate files (but same folder?)
Each UA in a scenario will keep the same IP address.

## Task breakdown

- [x]   Support 1 call per test (-m 1): default mode
- [x]   Add unit-tests for 1 call per test
- [x]   Support N calls per test (-m N)
- [x]   Add unit-tests for N calls per test
- [x]  Change documentation
